import datetime
NOW = datetime.datetime.now()

YEAR_START = 2000
BILLBOARD_YEAR_START = 2000
YEAR_END = NOW.year + 1
YEAR_SERIES = range(YEAR_START, YEAR_END)
BILLBOARD_YEAR_SERIES = range(BILLBOARD_YEAR_START, YEAR_END)
