/**
 * Song Lyrics & Popularity (SLAP)
 * This API provides the metrics and the metadata of songs in order to analyze Lyrics & Popularity
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Genre model module.
 * @module model/Genre
 * @version 1.0.0
 */
class Genre {
    /**
     * Constructs a new <code>Genre</code>.
     * @alias module:model/Genre
     */
    constructor() { 
        
        Genre.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Genre</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Genre} obj Optional instance to populate.
     * @return {module:model/Genre} The populated <code>Genre</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Genre();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('genre_id')) {
                obj['genre_id'] = ApiClient.convertToType(data['genre_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Genre.prototype['name'] = undefined;

/**
 * @member {String} genre_id
 */
Genre.prototype['genre_id'] = undefined;






export default Genre;

