/**
 * Song Lyrics & Popularity (SLAP)
 * This API provides the metrics and the metadata of songs in order to analyze Lyrics & Popularity
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SongMetricsRepetitionBow model module.
 * @module model/SongMetricsRepetitionBow
 * @version 1.0.0
 */
class SongMetricsRepetitionBow {
    /**
     * Constructs a new <code>SongMetricsRepetitionBow</code>.
     * @alias module:model/SongMetricsRepetitionBow
     */
    constructor() { 
        
        SongMetricsRepetitionBow.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SongMetricsRepetitionBow</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SongMetricsRepetitionBow} obj Optional instance to populate.
     * @return {module:model/SongMetricsRepetitionBow} The populated <code>SongMetricsRepetitionBow</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SongMetricsRepetitionBow();

            if (data.hasOwnProperty('frequencies')) {
                obj['frequencies'] = ApiClient.convertToType(data['frequencies'], ['Number']);
            }
            if (data.hasOwnProperty('words')) {
                obj['words'] = ApiClient.convertToType(data['words'], ['String']);
            }
            if (data.hasOwnProperty('ranks')) {
                obj['ranks'] = ApiClient.convertToType(data['ranks'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} frequencies
 */
SongMetricsRepetitionBow.prototype['frequencies'] = undefined;

/**
 * @member {Array.<String>} words
 */
SongMetricsRepetitionBow.prototype['words'] = undefined;

/**
 * @member {Array.<Number>} ranks
 */
SongMetricsRepetitionBow.prototype['ranks'] = undefined;






export default SongMetricsRepetitionBow;

