/**
 * Song Lyrics & Popularity (SLAP)
 * This API provides the metrics and the metadata of songs in order to analyze Lyrics & Popularity
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SongMetricsChart model module.
 * @module model/SongMetricsChart
 * @version 1.0.0
 */
class SongMetricsChart {
    /**
     * Constructs a new <code>SongMetricsChart</code>.
     * @alias module:model/SongMetricsChart
     */
    constructor() { 
        
        SongMetricsChart.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SongMetricsChart</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SongMetricsChart} obj Optional instance to populate.
     * @return {module:model/SongMetricsChart} The populated <code>SongMetricsChart</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SongMetricsChart();

            if (data.hasOwnProperty('library')) {
                obj['library'] = ApiClient.convertToType(data['library'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} library
 */
SongMetricsChart.prototype['library'] = undefined;

/**
 * @member {String} type
 */
SongMetricsChart.prototype['type'] = undefined;






export default SongMetricsChart;

