/**
 * Song Lyrics & Popularity (SLAP)
 * This API provides the metrics and the metadata of songs in order to analyze Lyrics & Popularity
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SlapClient);
  }
}(this, function(expect, SlapClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SlapClient.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('listSongWordFrequencyPlots', function() {
      it('should call listSongWordFrequencyPlots successfully', function(done) {
        //uncomment below and update the code to test listSongWordFrequencyPlots
        //instance.listSongWordFrequencyPlots(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listWordFrequencys', function() {
      it('should call listWordFrequencys successfully', function(done) {
        //uncomment below and update the code to test listWordFrequencys
        //instance.listWordFrequencys(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listWordRandomizations', function() {
      it('should call listWordRandomizations successfully', function(done) {
        //uncomment below and update the code to test listWordRandomizations
        //instance.listWordRandomizations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listWords', function() {
      it('should call listWords successfully', function(done) {
        //uncomment below and update the code to test listWords
        //instance.listWords(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveRepetitionMatrixPlot', function() {
      it('should call retrieveRepetitionMatrixPlot successfully', function(done) {
        //uncomment below and update the code to test retrieveRepetitionMatrixPlot
        //instance.retrieveRepetitionMatrixPlot(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveSong', function() {
      it('should call retrieveSong successfully', function(done) {
        //uncomment below and update the code to test retrieveSong
        //instance.retrieveSong(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('slapFlaskPublicControllersSongsGetParameterizedWordPopularitySingle', function() {
      it('should call slapFlaskPublicControllersSongsGetParameterizedWordPopularitySingle successfully', function(done) {
        //uncomment below and update the code to test slapFlaskPublicControllersSongsGetParameterizedWordPopularitySingle
        //instance.slapFlaskPublicControllersSongsGetParameterizedWordPopularitySingle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('slapFlaskPublicControllersSongsGetSong', function() {
      it('should call slapFlaskPublicControllersSongsGetSong successfully', function(done) {
        //uncomment below and update the code to test slapFlaskPublicControllersSongsGetSong
        //instance.slapFlaskPublicControllersSongsGetSong(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('slapFlaskPublicControllersSongsGetSongGenres', function() {
      it('should call slapFlaskPublicControllersSongsGetSongGenres successfully', function(done) {
        //uncomment below and update the code to test slapFlaskPublicControllersSongsGetSongGenres
        //instance.slapFlaskPublicControllersSongsGetSongGenres(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('slapFlaskPublicControllersSongsGetSongMetrics', function() {
      it('should call slapFlaskPublicControllersSongsGetSongMetrics successfully', function(done) {
        //uncomment below and update the code to test slapFlaskPublicControllersSongsGetSongMetrics
        //instance.slapFlaskPublicControllersSongsGetSongMetrics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('slapFlaskPublicControllersSongsGetSongs', function() {
      it('should call slapFlaskPublicControllersSongsGetSongs successfully', function(done) {
        //uncomment below and update the code to test slapFlaskPublicControllersSongsGetSongs
        //instance.slapFlaskPublicControllersSongsGetSongs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('slapListRepetitionPopularityPlots', function() {
      it('should call slapListRepetitionPopularityPlots successfully', function(done) {
        //uncomment below and update the code to test slapListRepetitionPopularityPlots
        //instance.slapListRepetitionPopularityPlots(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
