/**
 * Song Lyrics & Popularity (SLAP)
 * This API provides the metrics and the metadata of songs in order to analyze Lyrics & Popularity
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SlapClient);
  }
}(this, function(expect, SlapClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SlapClient.Song();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Song', function() {
    it('should create an instance of Song', function() {
      // uncomment below and update the code to test Song
      //var instane = new SlapClient.Song();
      //expect(instance).to.be.a(SlapClient.Song);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SlapClient.Song();
      //expect(instance).to.be();
    });

    it('should have the property artists (base name: "artists")', function() {
      // uncomment below and update the code to test the property artists
      //var instane = new SlapClient.Song();
      //expect(instance).to.be();
    });

    it('should have the property genres (base name: "genres")', function() {
      // uncomment below and update the code to test the property genres
      //var instane = new SlapClient.Song();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new SlapClient.Song();
      //expect(instance).to.be();
    });

    it('should have the property lyrics (base name: "lyrics")', function() {
      // uncomment below and update the code to test the property lyrics
      //var instane = new SlapClient.Song();
      //expect(instance).to.be();
    });

    it('should have the property compressibility (base name: "compressibility")', function() {
      // uncomment below and update the code to test the property compressibility
      //var instane = new SlapClient.Song();
      //expect(instance).to.be();
    });

    it('should have the property spotifyPopularity (base name: "spotify_popularity")', function() {
      // uncomment below and update the code to test the property spotifyPopularity
      //var instane = new SlapClient.Song();
      //expect(instance).to.be();
    });

  });

}));
