# Generated by Django 3.1.3 on 2020-12-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_popularity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
