# Generated by Django 3.1.3 on 2020-12-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_song_spotify_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('view_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('default_language', models.CharField(max_length=10)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.song')),
            ],
        ),
        migrations.CreateModel(
            name='BillboardYearEndEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.song')),
            ],
        ),
    ]
