# Generated by Django 3.1.3 on 2020-12-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_billboardyearendentry_youtubevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255)),
                ('album_id', models.CharField(max_length=255)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.song')),
            ],
        ),
    ]
