# Generated by Django 3.1.3 on 2020-12-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_spotifytrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='channel_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='default_language',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
