# Generated by Django 3.1.3 on 2020-12-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201202_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='comment_count',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='dislike_count',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='favorite_count',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='like_count',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='view_count',
            field=models.BigIntegerField(),
        ),
    ]
