# Generated by Django 3.1.3 on 2020-12-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201202_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifySongWeeklyStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streams', models.BigIntegerField()),
                ('week_date', models.CharField(max_length=255)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.song')),
            ],
        ),
    ]
