# Generated by Django 3.1.3 on 2020-12-04 16:04

import app.models.artists
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_spotifysongweeklystream'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(app.models.artists.ArtistRoleInSong['Collaborator'], 'collaborator'), (app.models.artists.ArtistRoleInSong['Featured'], 'featured')], max_length=64)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song')),
            ],
        ),
        # migrations.AlterField(
        #     model_name='song',
        #     name='artists',
        #     field=models.ManyToManyField(through='app.ArtistInSong', to='app.Artist'),
        # ),
        migrations.RemoveField(
            model_name='song',
            name='artists',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(through='app.ArtistInSong', to='app.Artist'),
        ),
    ]
