# Generated by Django 3.1.3 on 2020-12-06 02:06

import app.models.artists
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201204_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=289)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='pretty_name',
            field=models.CharField(default='', max_length=289),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistinsong',
            name='role',
            field=models.CharField(choices=[(app.models.artists.ArtistRoleInSong['Primary'], 'primary'), (app.models.artists.ArtistRoleInSong['Secondary'], 'secondary'), (app.models.artists.ArtistRoleInSong['Collaborator'], 'collaborator'), (app.models.artists.ArtistRoleInSong['Featured'], 'featured')], max_length=64),
        ),
        migrations.CreateModel(
            name='WordOccurrenceInSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appears_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wordcache')),
            ],
        ),
    ]
