# Generated by Django 3.1.3 on 2020-12-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201206_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcache',
            name='frequency',
        ),
        migrations.AddField(
            model_name='wordcache',
            name='occurs_in_song',
            field=models.ManyToManyField(through='app.WordOccurrenceInSong', to='app.Song'),
        ),
        migrations.AddField(
            model_name='wordoccurrenceinsong',
            name='frequency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
