# Generated by Django 3.1.3 on 2020-12-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201206_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinsong',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('collaborator', 'Collaborator'), ('featured', 'Featured')], max_length=64),
        ),
    ]
