# Generated by Django 3.1.3 on 2020-12-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_artistakas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artistinsong',
            unique_together={('artist', 'song')},
        ),
    ]
