# Generated by Django 3.1.3 on 2020-12-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201217_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='comment_count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='dislike_count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='favorite_count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='like_count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='view_count',
            field=models.BigIntegerField(null=True),
        ),
    ]
