# Generated by Django 3.1.3 on 2020-12-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201218_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytrack',
            name='album_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifytrack',
            name='track_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
