# Generated by Django 3.1.3 on 2020-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201218_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genius_id',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
