# Generated by Django 3.1.3 on 2020-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_wordcache_popularity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcache',
            name='popularity_score',
            field=models.FloatField(null=True),
        ),
    ]
